mesh:

  file: cube.pmsh

discretization:

  quadrature:
    xi: 2
    eta: 2
    zeta: 2

  dof_ordering:
    type: interleaved

materials:

  conductivity:
    type: constant
    value: 1.0
    unit: W/(m*K)

physics:

  models:

    source:
      type: volumetric
      read:
        mode: expression
        expression: "0.0"
        unit: W/m^3

boundary_conditions:

  - boundary: 0
    type: value
    read:
      mode: expression
      expression: "(1-x)*(1-y)*(1-z)"
      unit: K
    forms: [value_bc]
    model: constant

  - boundary: 1
    type: value
    read:
      mode: expression
      expression: "(1-x)*(1-y)*(1-z)"
      unit: K
    forms: [value_bc]
    model: constant

  - boundary: 2
    type: value
    read:
      mode: expression
      expression: "(1-x)*(1-y)*(1-z)"
      unit: K
    forms: [value_bc]
    model: constant

  - boundary: 3
    type: value
    read:
      mode: expression
      expression: "(1-x)*(1-y)*(1-z)"
      unit: K
    forms: [value_bc]
    model: constant

  - boundary: 4
    type: value
    read:
      mode: expression
      expression: "(1-x)*(1-y)*(1-z)"
      unit: K
    forms: [value_bc]
    model: constant

  - boundary: 5
    type: value
    read:
      mode: expression
      expression: "(1-x)*(1-y)*(1-z)"
      unit: K
    forms: [value_bc]
    model: constant

initial_condition:
  read:
    mode: expression
    expression: "0.0"
    unit: K

solver:

  driver:
    type: steady

  linear:

    type: cg

    operator:
      type: fem

    preconditioner:
      type: identity

    tolerance: 1.0e-12
    max_iterations: 10000

output:
  directory: output
  write_frequency: 1
  prefix: block3d_constant_conductivity_solution

logging:

  linear:
    type: console
    interval: 10

  driver:
    type: console

  output:
    file: log.txt
